#!/usr/bin/env python3
"""Generate os_tests.mm0 (the contract) and gen/cases.inc (the runtime table)
from manifest.py.

    ./gen.py            rewrite the generated files
    ./gen.py --check    fail (with a diff) if a committed file is stale

The .mm0 carries one theorem *statement* per test; the proofs live in the
hand-written os_tests.mm1, and `mm0-c` ties the two together, so this generator
never has to be trusted -- a wrong statement stops the proof discharging it.

gen/cases.inc is the same rows as a C table for the harness. The harness applies
expectations, it never recomputes them, so `code = rdi & 0xff` is done here.

Literals are `:x` chains of hex digits with no leading zeros, matching how
peano_hex's `,0x...` splices elaborate in the .mm1 -- the terms must be
identical, not merely equal.
"""

import argparse
import difflib
import os
import sys

import manifest

HERE = os.path.dirname(os.path.abspath(__file__))


def mm0_nat(n: int) -> str:
    """A nat literal as a `:x` chain of hex digits with no leading zeros, the way
    a `,0x...` splice elaborates it: `x0`, `x1`, `xf :x xf`, `x1 :x x0 :x x0`."""
    assert n >= 0
    return " :x ".join("x" + d for d in format(n, "x"))


def mm0_str(data: bytes) -> str:
    """A string literal as the `ch _ _ ': … ': s1 (ch _ _)` term a `,"…"` splice
    elaborates to -- each byte `ch x<hi> x<lo>`, joined by string cons `':`."""
    def ch(b: int) -> str:
        return f"ch x{b >> 4:x} x{b & 0xf:x}"
    if not data:
        return "s0"
    chs = [ch(b) for b in data]
    if len(chs) == 1:
        return f"s1 ({chs[0]})"
    return " ': ".join(chs[:-1]) + f" ': s1 ({chs[-1]})"


def wrap_doc(doc: str) -> str:
    # One `--|` block; keep it simple, one line is fine for these.
    import textwrap
    lines = textwrap.wrap(doc, 74)
    return "\n".join("--| " + l for l in lines)


def gen_mm0() -> str:
    out = [
        "-- GENERATED by gen.py from manifest.py -- do not edit.",
        "--",
        "-- The OS-layer spec test suite's contract. One theorem *statement* per",
        "-- test, proved in os_tests.mm1 and checked against this file by mm0-c.",
        "-- The suite is the formal half of tests/spec-x86/os-audit/: each theorem",
        "-- is a positive fact a real syscall confirms.",
        "--",
        "-- Declaration order is manifest order, and os_tests.mm1 must follow it.",
        "",
        'import "../spec_lib.mm0";',
        "",
    ]
    for t in manifest.TESTS:
        out.append(wrap_doc(t.doc))
        out.append(f"theorem {t.name} (k: nat)")
        out.append("  (hk:   $ k e. Config $)")
        out.append("  (hex:  $ readException k = suc exSysCall $)")
        out.append(f"  (hrax: $ readReg k RAX = {mm0_nat(0x3c)} $)")      # sys_exit
        out.append(f"  (hrdi: $ readReg k RDI = {mm0_nat(t.rdi)} $):")
        out.append(f"  $ execExit k ({mm0_nat(t.code)}) $;")
        out.append("")
    for t in manifest.FAULT_TESTS:
        out.append(wrap_doc(t.doc))
        if t.fault_addr is None:
            out.append(f"theorem {t.name} {{k2: nat}} (k: nat)")
            out.append("  (hk:   $ k e. Config $)")
            out.append("  (hexc: $ readException k = 0 $)")           # normal running state
            out.append(f"  (hc:   $ readMemX k (readRIP k) ({mm0_str(t.instr)}) $):")  # faulting instr at RIP
        else:
            # A memory-write fault: the store target `fault_addr` is a non-writable
            # page, stated as `getMemory k @ addr = prot, b2 /\ ~(PROT_WRITE C_ prot)`.
            out.append(f"theorem {t.name} {{k2: nat}} (k prot b2: nat)")
            out.append("  (hk:   $ k e. Config $)")
            out.append("  (hexc: $ readException k = 0 $)")           # normal running state
            out.append(f"  (hc:   $ readMemX k (readRIP k) ({mm0_str(t.instr)}) $)")  # faulting instr at RIP
            # parenthesize the address: `@` binds tighter than the `:x` hex chain.
            out.append(f"  (hpage: $ getMemory k @ ({mm0_nat(t.fault_addr)}) = prot, b2 $)")  # target page
            out.append("  (hnw:  $ ~(PROT_WRITE C_ prot) $):")        # not writable -> #GP
        out.append(f"  $ E. k2 (step k k2 /\\ execExit k2 ({mm0_nat(t.code)})) $;")
        out.append("")
    for t in manifest.MMAP_TESTS:
        out.append(wrap_doc(t.doc))
        out.append(f"theorem {t.name} {{k2 m2: nat}} (i o k m: nat)")
        out.append("  (hi:    $ i e. List u8 $) (ho: $ o e. List u8 $)")
        out.append("  (hk:    $ k e. Config $)")
        out.append("  (hm:    $ m e. PageMapping (getMemory k) $)")
        out.append("  (hex:   $ readException k = suc exSysCall $)")
        out.append(f"  (hrax:  $ readReg k RAX = {mm0_nat(9)} $)")         # sys_mmap
        out.append(f"  (hrdi:  $ readReg k RDI = {mm0_nat(0)} $)")
        out.append(f"  (hflags: $ readReg k 10 = {mm0_nat(t.flags)} $)")   # MAP_PRIVATE[|MAP_ANONYMOUS]
        out.append(f"  (hfd:   $ readReg k 8 = {mm0_nat(t.fd % (1 << 64))} $)")  # fd (read as 32 bits)
        out.append(f"  (hrdx:  $ readReg k RDX = {mm0_nat(t.prot)} $)")    # PROT_READ
        out.append(f"  (hoff:  $ readReg k 9 = {mm0_nat(0)} $):")
        out.append("  $ E. k2 E. m2 (execIO (mkKS i o k m) (mkKS i o k2 m2) /\\")
        out.append(f"      readReg k2 RAX = {mm0_nat(t.ret)}) $;")
        out.append("")
    for t in manifest.MMAP_OK_TESTS:
        out.append(wrap_doc(t.doc))
        out.append(f"theorem {t.name} {{k2 m2 k3 pad buf j: nat}} (i o k m k2m mv rv kw: nat)")
        out.append("  (hi:    $ i e. List u8 $) (ho: $ o e. List u8 $)")
        out.append("  (hk:    $ k e. Config $)")
        out.append("  (hm:    $ m e. PageMapping (getMemory k) $)")
        out.append("  (hex:   $ readException k = suc exSysCall $)")
        out.append(f"  (hrax:  $ readReg k RAX = {mm0_nat(9)} $)")         # sys_mmap
        out.append(f"  (hrdi:  $ readReg k RDI = {mm0_nat(0)} $)")
        out.append(f"  (hflags: $ readReg k 10 = {mm0_nat(t.flags)} $)")   # MAP_PRIVATE|MAP_ANONYMOUS
        out.append(f"  (hprot: $ readReg k RDX = {mm0_nat(t.prot)} $)")    # PROT_READ|PROT_WRITE
        out.append(f"  (hfd:   $ readReg k 8 = {mm0_nat(t.fd % (1 << 64))} $)")  # anon fd = -1
        out.append(f"  (hoff:  $ readReg k 9 = {mm0_nat(0)} $)")
        out.append("  (hu64:  $ rv e. u64 $)")
        out.append("  (hnoterr: $ ~isIOError rv $)")
        # the mmap memory effect (mapMem + the zeroed buffer) is abstract
        out.append("  (hmap:  $ E. pad E. buf (buf e. Array u8 (readReg (setException k 0) RSI + pad) /\\")
        out.append("      (MAP_ANONYMOUS C_ MAP_PRIVATE + MAP_ANONYMOUS -> all (sn 0) buf) /\\")
        out.append("      A. j (j < readReg (setException k 0) RSI + pad -> m @ (rv +_64 j) = 0) /\\")
        out.append("      mapMem (readReg (setException k 0) RDX) (setException k 0) m rv buf k2m mv) $)")
        # the returned buffer supports a write (abstract; the harness does it for real)
        nul = mm0_str(b"\x00")   # the null byte, as `,"\x00"` elaborates
        out.append(f"  (hwr:   $ writeMem (setReg k2m RAX rv) rv ({nul}) kw /\\ readException kw = 0 $):")
        out.append("  $ E. k2 E. m2 (execIO (mkKS i o k m) (mkKS i o k2 m2) /\\")
        out.append(f"      E. k3 (writeMem k2 (readReg k2 RAX) ({nul}) k3 /\\ readException k3 = 0)) $;")
        out.append("")
    for t in manifest.WRITE_TESTS:
        buf, n = mm0_str(t.data), len(t.data)
        out.append(wrap_doc(t.doc))
        out.append(f"theorem {t.name} {{k2 m2: nat}} (i o k m: nat)")
        out.append("  (hi:    $ i e. List u8 $) (ho: $ o e. List u8 $)")
        out.append("  (hk:    $ k e. Config $)")
        out.append("  (hm:    $ m e. PageMapping (getMemory k) $)")
        out.append("  (hex:   $ readException k = suc exSysCall $)")
        out.append(f"  (hrax:  $ readReg k RAX = {mm0_nat(1)} $)")         # sys_write
        out.append(f"  (hrdi:  $ readReg k RDI = {mm0_nat(t.fd)} $)")
        out.append(f"  (hrdx:  $ readReg k RDX = {mm0_nat(n)} $)")
        out.append(f"  (hbuf:  $ readMem k (readReg k RSI) ({buf}) $):")
        out.append("  $ E. k2 E. m2 (execIO (mkKS i o k m)")
        out.append(f"      (mkKS i (o ++ ({buf})) k2 m2) /\\ readReg k2 RAX = {mm0_nat(n)}) $;")
        out.append("")
    for t in manifest.WRITE_ERRNO_TESTS:
        ret = (1 << 64) - t.errno
        out.append(wrap_doc(t.doc))
        out.append(f"theorem {t.name} {{k2 m2: nat}} (i o k m buf: nat)")
        out.append("  (hi:    $ i e. List u8 $) (ho: $ o e. List u8 $)")
        out.append("  (hk:    $ k e. Config $)")
        out.append("  (hm:    $ m e. PageMapping (getMemory k) $)")
        out.append("  (hex:   $ readException k = suc exSysCall $)")
        out.append(f"  (hrax:  $ readReg k RAX = {mm0_nat(1)} $)")         # sys_write
        out.append(f"  (hrdi:  $ readReg k RDI = {mm0_nat(t.fd)} $)")
        out.append(f"  (hrdx:  $ readReg k RDX = {mm0_nat(t.count)} $)")
        out.append("  (hbuf:  $ readMem k (readReg k RSI) buf $)")
        out.append(f"  (hbufA: $ buf e. Array u8 {mm0_nat(t.count)} $):")
        out.append("  $ E. k2 E. m2 (execIO (mkKS i o k m) (mkKS i o k2 m2) /\\")
        out.append(f"      readReg k2 RAX = {mm0_nat(ret)}) $;")
        out.append("")
    for t in manifest.READ_TESTS:
        l1, n = mm0_str(t.data), len(t.data)
        out.append(wrap_doc(t.doc))
        out.append(f"theorem {t.name} {{k2 m2: nat}} (i o k m buf kw: nat)")
        out.append("  (hi:    $ i e. List u8 $) (ho: $ o e. List u8 $)")
        out.append("  (hk:    $ k e. Config $)")
        out.append("  (hm:    $ m e. PageMapping (getMemory k) $)")
        out.append("  (hex:   $ readException k = suc exSysCall $)")
        out.append(f"  (hrax:  $ readReg k RAX = {mm0_nat(0)} $)")         # sys_read
        out.append(f"  (hrdi:  $ readReg k RDI = {mm0_nat(0)} $)")
        out.append(f"  (hrdx:  $ readReg k RDX = {mm0_nat(n)} $)")
        out.append("  (hbuf:  $ readMem k (readReg k RSI) buf $)")
        out.append(f"  (hbufA: $ buf e. Array u8 {mm0_nat(n)} $)")
        out.append(f"  (hwrite: $ writeMem (setException k 0) (readReg k RSI) ({l1}) kw $)")
        out.append("  (hkw:   $ readException kw = 0 $):")
        out.append("  $ E. k2 E. m2 (execIO (mkKS i o k m)")
        out.append(f"      (mkKS (i ++ ({l1})) o k2 m2) /\\ readReg k2 RAX = {mm0_nat(n)}) $;")
        out.append("")
    for t in manifest.READ_ERRNO_TESTS:
        ret = (1 << 64) - t.errno
        out.append(wrap_doc(t.doc))
        out.append(f"theorem {t.name} {{k2 m2: nat}} (i o k m buf: nat)")
        out.append("  (hi:    $ i e. List u8 $) (ho: $ o e. List u8 $)")
        out.append("  (hk:    $ k e. Config $)")
        out.append("  (hm:    $ m e. PageMapping (getMemory k) $)")
        out.append("  (hex:   $ readException k = suc exSysCall $)")
        out.append(f"  (hrax:  $ readReg k RAX = {mm0_nat(0)} $)")         # sys_read
        out.append(f"  (hrdi:  $ readReg k RDI = {mm0_nat(t.fd)} $)")
        out.append(f"  (hrdx:  $ readReg k RDX = {mm0_nat(t.count)} $)")
        out.append("  (hbuf:  $ readMem k (readReg k RSI) buf $)")
        out.append(f"  (hbufA: $ buf e. Array u8 {mm0_nat(t.count)} $):")
        out.append("  $ E. k2 E. m2 (execIO (mkKS i o k m) (mkKS i o k2 m2) /\\")
        out.append(f"      readReg k2 RAX = {mm0_nat(ret)}) $;")
        out.append("")
    for t in manifest.OPEN_ERRNO_TESTS:
        ret = (1 << 64) - t.errno
        nt = mm0_str(t.path.encode() + b"\x00")   # the null-terminated filename bytes
        out.append(wrap_doc(t.doc))
        out.append(f"theorem {t.name} {{k2 m2: nat}} (i o k m: nat)")
        out.append("  (hi:    $ i e. List u8 $) (ho: $ o e. List u8 $)")
        out.append("  (hk:    $ k e. Config $)")
        out.append("  (hm:    $ m e. PageMapping (getMemory k) $)")
        out.append("  (hex:   $ readException k = suc exSysCall $)")
        out.append(f"  (hrax:  $ readReg k RAX = {mm0_nat(2)} $)")         # sys_open
        out.append(f"  (hmem:  $ readMem k (readReg k RDI) ({nt}) $)")     # the filename bytes at RDI
        out.append(f"  (hrsi:  $ readReg k RSI = {mm0_nat(0)} $)")         # O_RDONLY
        out.append(f"  (hrdx:  $ readReg k RDX = {mm0_nat(0)} $):")        # mode (unused)
        out.append("  $ E. k2 E. m2 (execIO (mkKS i o k m) (mkKS i o k2 m2) /\\")
        out.append(f"      readReg k2 RAX = {mm0_nat(ret)}) $;")
        out.append("")
    for t in manifest.OPEN_OK_TESTS:
        nt = mm0_str(t.path.encode() + b"\x00")   # the null-terminated filename bytes
        out.append(wrap_doc(t.doc))
        out.append(f"theorem {t.name} {{k2 m2 ret: nat}} (i o k m: nat)")
        out.append("  (hi:    $ i e. List u8 $) (ho: $ o e. List u8 $)")
        out.append("  (hk:    $ k e. Config $)")
        out.append("  (hm:    $ m e. PageMapping (getMemory k) $)")
        out.append("  (hex:   $ readException k = suc exSysCall $)")
        out.append(f"  (hrax:  $ readReg k RAX = {mm0_nat(2)} $)")         # sys_open
        out.append(f"  (hmem:  $ readMem k (readReg k RDI) ({nt}) $)")     # the filename bytes at RDI
        out.append(f"  (hrsi:  $ readReg k RSI = {mm0_nat(0)} $)")         # O_RDONLY
        out.append(f"  (hrdx:  $ readReg k RDX = {mm0_nat(0)} $):")        # mode (unused)
        out.append("  $ E. k2 E. m2 E. ret (execIO (mkKS i o k m) (mkKS i o k2 m2) /\\")
        out.append("      readReg k2 RAX = ret /\\ ~isIOError ret) $;")   # a good (non-error) fd exists
        out.append("")
    for t in manifest.FSTAT_ERRNO_TESTS:
        ret = (1 << 64) - t.errno
        out.append(wrap_doc(t.doc))
        out.append(f"theorem {t.name} {{k2 m2: nat}} (i o k m stat stat2 kw: nat)")
        out.append("  (hi:    $ i e. List u8 $) (ho: $ o e. List u8 $)")
        out.append("  (hk:    $ k e. Config $)")
        out.append("  (hm:    $ m e. PageMapping (getMemory k) $)")
        out.append("  (hex:   $ readException k = suc exSysCall $)")
        out.append(f"  (hrax:  $ readReg k RAX = {mm0_nat(5)} $)")         # sys_fstat
        out.append(f"  (hrdi:  $ readReg k RDI = {mm0_nat(t.fd)} $)")      # bad fd
        out.append("  (hstat:  $ readMem k (readReg k RSI) stat $)")
        out.append("  (hstatA: $ stat e. Stat $)")
        out.append("  (hstat2A: $ stat2 e. Stat $)")
        out.append("  (hwrite: $ writeMem (setException k 0) (readReg k RSI) stat2 kw $):")
        out.append("  $ E. k2 E. m2 (execIO (mkKS i o k m) (mkKS i o k2 m2) /\\")
        out.append(f"      readReg k2 RAX = {mm0_nat(ret)}) $;")
        out.append("")
    for t in manifest.FSTAT_OK_TESTS:
        out.append(wrap_doc(t.doc))
        out.append(f"theorem {t.name} {{k2 m2: nat}} (i o k m stat stat2 kw: nat)")
        out.append("  (hi:    $ i e. List u8 $) (ho: $ o e. List u8 $)")
        out.append("  (hk:    $ k e. Config $)")
        out.append("  (hm:    $ m e. PageMapping (getMemory k) $)")
        out.append("  (hex:   $ readException k = suc exSysCall $)")
        out.append(f"  (hrax:  $ readReg k RAX = {mm0_nat(5)} $)")         # sys_fstat
        out.append(f"  (hrdi:  $ readReg k RDI = {mm0_nat(t.fd)} $)")      # valid fd
        out.append("  (hstat:  $ readMem k (readReg k RSI) stat $)")
        out.append("  (hstatA: $ stat e. Stat $)")
        out.append("  (hstat2A: $ stat2 e. Stat $)")
        out.append("  (hwrite: $ writeMem (setException k 0) (readReg k RSI) stat2 kw $)")
        out.append("  (hkw:   $ readException kw = 0 $):")
        out.append("  $ E. k2 E. m2 (execIO (mkKS i o k m) (mkKS i o k2 m2) /\\")
        out.append(f"      readReg k2 RAX = {mm0_nat(0)}) $;")
        out.append("")
    return "\n".join(out)


def gen_cases() -> str:
    out = [
        "/* GENERATED by gen.py from manifest.py -- do not edit. */",
        "/* One row per exit test: the syscall's RDI, and the exit code the parent",
        "   must observe (RDI & 0xff). #include'd inside an array initializer. */",
    ]
    for t in manifest.TESTS:
        out.append(f'{{ "{t.name}", {t.rdi:#x}ULL, {t.code} }},')
    out.append("")
    return "\n".join(out)


def gen_fault_cases() -> str:
    out = [
        "/* GENERATED by gen.py from manifest.py -- do not edit. */",
        "/* One row per fault-exit test: the faulting instruction's raw bytes (the",
        "   same bytes the model decodes) and the exit code the parent must observe",
        "   (128 + signo, the shell's $? for a signal death). The harness copies the",
        "   bytes to an executable page and jumps to them. #include'd inside an array",
        "   initializer. */",
    ]
    for t in manifest.FAULT_TESTS:
        code = ", ".join(f"{b:#04x}" for b in t.instr)
        out.append(f'{{ "{t.name}", {{ {code} }}, {len(t.instr)}, {t.code} }},')
    out.append("")
    return "\n".join(out)


def gen_mmap_cases() -> str:
    out = [
        "/* GENERATED by gen.py from manifest.py -- do not edit. */",
        "/* One row per mmap test: the raw syscall argument registers and the",
        "   value the kernel must return in RAX (-errno). #include'd inside an",
        "   array initializer. */",
    ]
    for t in manifest.MMAP_TESTS:
        # ret is signed here: the harness compares against a raw long in RAX.
        out.append(f'{{ "{t.name}", {t.addr:#x}ULL, {t.length:#x}ULL, '
                   f'{t.prot:#x}ULL, {t.flags:#x}ULL, {t.fd}LL, {t.off:#x}ULL, '
                   f'{-t.errno}LL }},')
    out.append("")
    return "\n".join(out)


def gen_mmap_ok_cases() -> str:
    out = [
        "/* GENERATED by gen.py from manifest.py -- do not edit. */",
        "/* One row per mmap-ok test: the raw mmap argument registers (addr 0, off",
        "   0). The harness maps the region, writes to it via inline asm, and checks",
        "   the child does not crash. #include'd inside an array initializer. */",
    ]
    for t in manifest.MMAP_OK_TESTS:
        out.append(f'{{ "{t.name}", 0x0ULL, {t.length:#x}ULL, '
                   f'{t.prot:#x}ULL, {t.flags:#x}ULL, {t.fd}LL, 0x0ULL }},')
    out.append("")
    return "\n".join(out)


def gen_write_cases() -> str:
    out = [
        "/* GENERATED by gen.py from manifest.py -- do not edit. */",
        "/* One row per write test: the raw fd register, and the bytes to write",
        "   (count = the length). The harness captures fd 1 through a pipe and",
        "   checks the bytes arrived and RAX = count. #include'd inside an array",
        "   initializer. */",
    ]
    for t in manifest.WRITE_TESTS:
        data = ", ".join(str(b) for b in t.data)
        out.append(f'{{ "{t.name}", {t.fd:#x}ULL, {{ {data} }}, {len(t.data)} }},')
    out.append("")
    return "\n".join(out)


def gen_read_cases() -> str:
    out = [
        "/* GENERATED by gen.py from manifest.py -- do not edit. */",
        "/* One row per read test: the bytes to feed to stdin (count = the",
        "   length). The harness preloads stdin through a pipe, reads it back into",
        "   a buffer, and checks the bytes and RAX = count. #include'd inside an",
        "   array initializer. */",
    ]
    for t in manifest.READ_TESTS:
        data = ", ".join(str(b) for b in t.data)
        out.append(f'{{ "{t.name}", {{ {data} }}, {len(t.data)} }},')
    out.append("")
    return "\n".join(out)


def gen_write_errno_cases() -> str:
    out = [
        "/* GENERATED by gen.py from manifest.py -- do not edit. */",
        "/* One row per write-errno test: the raw fd register, the byte count, and",
        "   the value the kernel must return in RAX (-errno). The harness supplies a",
        "   scratch buffer. #include'd inside an array initializer. */",
    ]
    for t in manifest.WRITE_ERRNO_TESTS:
        out.append(f'{{ "{t.name}", {t.fd:#x}ULL, {t.count}, {-t.errno}L }},')
    out.append("")
    return "\n".join(out)


def gen_read_errno_cases() -> str:
    out = [
        "/* GENERATED by gen.py from manifest.py -- do not edit. */",
        "/* One row per read-errno test: the raw fd register, the byte count, and",
        "   the value the kernel must return in RAX (-errno). The harness supplies a",
        "   scratch buffer. #include'd inside an array initializer. */",
    ]
    for t in manifest.READ_ERRNO_TESTS:
        out.append(f'{{ "{t.name}", {t.fd:#x}ULL, {t.count}, {-t.errno}L }},')
    out.append("")
    return "\n".join(out)


def gen_open_errno_cases() -> str:
    out = [
        "/* GENERATED by gen.py from manifest.py -- do not edit. */",
        "/* One row per open-errno test: the (nonexistent) path to open and the",
        "   value the kernel must return in RAX (-errno). The harness makes the raw",
        "   open(2) syscall O_RDONLY. #include'd inside an array initializer. */",
    ]
    for t in manifest.OPEN_ERRNO_TESTS:
        path = t.path.replace("\\", "\\\\").replace('"', '\\"')
        out.append(f'{{ "{t.name}", "{path}", {-t.errno}L }},')
    out.append("")
    return "\n".join(out)


def gen_fstat_errno_cases() -> str:
    out = [
        "/* GENERATED by gen.py from manifest.py -- do not edit. */",
        "/* One row per fstat-errno test: the raw (bad) fd register and the value",
        "   the kernel must return in RAX (-errno). The harness supplies a scratch",
        "   stat buffer. #include'd inside an array initializer. */",
    ]
    for t in manifest.FSTAT_ERRNO_TESTS:
        out.append(f'{{ "{t.name}", {t.fd:#x}ULL, {-t.errno}L }},')
    out.append("")
    return "\n".join(out)


def gen_open_ok_cases() -> str:
    out = [
        "/* GENERATED by gen.py from manifest.py -- do not edit. */",
        "/* One row per open-ok test: a path to open; the kernel must return a valid",
        "   (non-negative) fd -- not an errno. The harness opens it and checks the",
        "   return is >= 0, then closes it. #include'd inside an array initializer. */",
    ]
    for t in manifest.OPEN_OK_TESTS:
        path = t.path.replace("\\", "\\\\").replace('"', '\\"')
        out.append(f'{{ "{t.name}", "{path}" }},')
    out.append("")
    return "\n".join(out)


def gen_fstat_ok_cases() -> str:
    out = [
        "/* GENERATED by gen.py from manifest.py -- do not edit. */",
        "/* One row per fstat-ok test: a valid fd; the kernel must return 0. The",
        "   harness supplies a scratch stat buffer. #include'd inside an array",
        "   initializer. */",
    ]
    for t in manifest.FSTAT_OK_TESTS:
        out.append(f'{{ "{t.name}", {t.fd:#x}ULL }},')
    out.append("")
    return "\n".join(out)


FILES = {
    "os_tests.mm0": gen_mm0,
    "gen/cases.inc": gen_cases,
    "gen/fault_cases.inc": gen_fault_cases,
    "gen/mmap_cases.inc": gen_mmap_cases,
    "gen/mmap_ok_cases.inc": gen_mmap_ok_cases,
    "gen/write_cases.inc": gen_write_cases,
    "gen/write_errno_cases.inc": gen_write_errno_cases,
    "gen/read_cases.inc": gen_read_cases,
    "gen/read_errno_cases.inc": gen_read_errno_cases,
    "gen/open_errno_cases.inc": gen_open_errno_cases,
    "gen/fstat_errno_cases.inc": gen_fstat_errno_cases,
    "gen/fstat_ok_cases.inc": gen_fstat_ok_cases,
    "gen/open_ok_cases.inc": gen_open_ok_cases,
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail with a diff if a committed file is stale")
    args = ap.parse_args()
    stale = False
    for rel, fn in FILES.items():
        path = os.path.join(HERE, rel)
        new = fn()
        old = ""
        if os.path.exists(path):
            with open(path) as f:
                old = f.read()
        if args.check:
            if old != new:
                stale = True
                sys.stderr.write(f"stale: {rel}\n")
                sys.stderr.writelines(difflib.unified_diff(
                    old.splitlines(True), new.splitlines(True),
                    fromfile=rel + " (committed)", tofile=rel + " (fresh)"))
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w") as f:
                f.write(new)
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
